How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)

What is the average age of men?

What is the percentage of people who have a Bachelor's degree?

What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?

What percentage of people without advanced education make more than 50K?

What is the minimum number of hours a person works per week?

What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?

What country has the highest percentage of people that earn >50K and what is that percentage?
Identify the most popular occupation for those who earn >50K in India.

In [ ]:
import pandas as pd
df=pd.read_csv('/content/1994_census_up.csv')
# Strip whitespace from column names
df.columns = df.columns.str.strip()

# Strip whitespace from string data
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
#  How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)

race_counts = df['race'].value_counts()
print(race_counts)

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [ ]:
#what is the average age of men
male_avg_age= df[df['sex'] == 'Male']["age"].mean()
print(male_avg_age)

39.43354749885268

In [ ]:
#what is the percentage of bachelor degree

bachelor=df[df["education"]=="Bachelors"]
total_bachelor=len(bachelor)
total_person=len(df)
percentage_bachelor=(total_bachelor/total_person)*100
print(f'{round(percentage_bachelor,2)}%')

16.45%

In [ ]:
# What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?
df_higher_edu=df[df["education"].isin(["Bachelors","Masters","Doctorate"])]
length_higher_degre=len(df_higher_edu[df_higher_edu["salary"]==">50K"])

percentage_earn_more_50k=length_higher_degre/total_person*100
print(f'{round(percentage_earn_more_50k,2)}%')

10.71%

In [ ]:
# What percentage of people without advanced education make more than 50K
df_lower_edu  = df["education"].value_counts()
print(df_lower_edu)

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [ ]:
morethan_50 = df[df["salary"]==">50K"]
print(morethan_50)

       age         workclass  fnlwgt     education  education-num  \
7       52  Self-emp-not-inc  209642       HS-grad              9
8       31           Private   45781       Masters             14
9       42           Private  159449     Bachelors             13
10      37           Private  280464  Some-college             10
11      30         State-gov  141297     Bachelors             13
...    ...               ...     ...           ...            ...
32539   71                 ?  287372     Doctorate             16
32545   39         Local-gov  111499    Assoc-acdm             12
32554   53           Private  321865       Masters             14
32557   40           Private  154374       HS-grad              9
32560   52      Self-emp-inc  287927       HS-grad              9

           marital-status         occupation   relationship  \
7      Married-civ-spouse    Exec-managerial        Husband
8           Never-married     Prof-specialty  Not-in-family
9      Married-civ-spouse    Exec-managerial        Husband
10     Married-civ-spouse    Exec-managerial        Husband
11     Married-civ-spouse     Prof-specialty        Husband
...                   ...                ...            ...
32539  Married-civ-spouse                  ?        Husband
32545  Married-civ-spouse       Adm-clerical           Wife
32554  Married-civ-spouse    Exec-managerial        Husband
32557  Married-civ-spouse  Machine-op-inspct        Husband
32560  Married-civ-spouse    Exec-managerial           Wife

                     race     sex  capital-gain  capital-loss  hours-per-week  \
7                   White    Male             0             0              45
8                   White  Female         14084             0              50
9                   White    Male          5178             0              40
10                  Black    Male             0             0              80
11     Asian-Pac-Islander    Male             0             0              40
...                   ...     ...           ...           ...             ...
32539               White    Male             0             0              10
32545               White  Female             0             0              20
32554               White    Male             0             0              40
32557               White    Male             0             0              40
32560               White  Female         15024             0              40

      native-country salary
7      United-States   >50K
8      United-States   >50K
9      United-States   >50K
10     United-States   >50K
11             India   >50K
...              ...    ...
32539  United-States   >50K
32545  United-States   >50K
32554  United-States   >50K
32557  United-States   >50K
32560  United-States   >50K

[7841 rows x 15 columns]

7841

In [ ]:
lower_degree=len(morethan_50)-length_higher_degre
percentage = lower_degree/total_person*100
print(f'{round(percentage,2)}%')

13.37%

In [ ]:
# What is the minimum number of hours a person works per week?
min_hours=df["hours-per-week"].min()
print(min_hours)

1

In [ ]:
# What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
min_max_earning=morethan_50[morethan_50["hours-per-week"]==1]


percentage_min_work_mas_earn=len(min_max_earning)/total_person*100
print(f'{round(percentage_min_work_mas_earn,2)}%')

0.01%

In [ ]:
# What country has the highest percentage of people that earn >50K and what is that percentage?
# Identify the most popular occupation for those who earn >50K in India.

In [ ]:
total_country=morethan_50["native-country"].value_counts()   #value_counts method give  dictionary
# print(total_country)
higher_earn_country=total_country["United-States"]/total_person*100
print(f'{round(higher_earn_country,2)}%')

22.02%

In [ ]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
#Identify the most popular occupation for those who earn >50K in India.
morethan50k_earn_in_india=morethan_50[morethan_50["native-country"] =='India']
# print(morethan50k_earn_in_india)

mostpapular_occupation=morethan50k_earn_in_india["occupation"].value_counts()
print(mostpapular_occupation)

occupation
Prof-specialty      25
Exec-managerial      8
Other-service        2
Tech-support         2
Transport-moving     1
Sales                1
Adm-clerical         1
Name: count, dtype: int64